name: Deploy to Vultr

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "."
          target: "/var/www/policy-pulse"
          strip_components: 0

      - name: Install & restart on server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            set -e
            cd /var/www/policy-pulse
            curl -fsSL https://deb.nodesource.com/setup_20.x | bash - || true
            apt-get install -y nodejs || true
            npm i -g pm2 || true
            npm ci
            pm2 startOrReload ecosystem.config.cjs || pm2 start server.js --name policy-pulse
            pm2 save
